#gateway
info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  mappings:
    sensitive: false

zuul:
  prefix: /api
  routes:
    user: 
      path: /user/**
      serviceId: user-service
    ticket: 
      path: /ticket/**
      serviceId: ticket-service         
      

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    registerWithEureka: true
      
server:
  port: 8765
  
spring:
  application:
    name: gateway-service

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

    