#ticket
server:  
  port: ${PORT:3315}

spring:  
  application:
    name: ticket-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8762}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true
    
#spring.datasource.schema: ticket-system
#spring.jpa.properties.hibernate.default_schema: ticket-system

spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://ec2-52-53-223-216.us-west-1.compute.amazonaws.com:9101/postgres
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username: postgres
spring.datasource.password: hackamania2017
spring.jpa.show-sql: true

spring.aop.auto: true

spring.jpa.properties.hibernate.show_sql: false
spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true
#Runs the 'data.sql' file in your resources directory
spring.datasource.initialize: false

#Don't use this property it can mess up the database
spring.jpa.hibernate.ddl-auto: create