#ticket
server:  
  port: 2223

spring:  
  application:
    name: ticket-service
  jpa:
    database: ORACLE
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password:
    platform: oracle
    driver-class-name: org.h2.Driver
  

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8762}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

